### PR TITLE
Add More simulator counter values

### PR DESCRIPTION
**Pull request by kbrock**
## Description

For the simulator, we wanted more values

## Type of change

Please mark options that are relevant:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update
- [ ] Build related change

## How Has This Been Tested?

When we run our app, it was fetching these metrics.
Before this change, no values were coming back.
After this change, values are coming back.

## Checklist:

- [x] My code follows the `CONTRIBUTION` [guidelines](https://github.com/vmware/govmomi/blob/main/CONTRIBUTING.md) of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

### CODE REVIEW

**Comment by kbrock** [comment]
update:
- run go fmt on the file in question (not sure if this is the error that lint was stating)

**Review by dougm — COMMENTED** [review]
Thanks @kbrock 
lgtm, but can you fixup the [commit message](https://github.com/vmware/govmomi/blob/main/CONTRIBUTING.md#format-of-the-commit-message)? It is useful so this change lands in the vcsim section of the generated release notes. Example:

```
vcsim: add PerformanceManager counter values
```

**Comment by kbrock** [comment]
update:
- changed commit message
update:
- squashed

thank you @dougm

**Review by dougm — APPROVED** [review]
Thanks @kbrock

**Comment by kbrock** [comment]
thank you @dougm - great project

**Pull request merged**
