### PR TITLE
Make optional bool fields pointers

### PR DESCRIPTION
**Pull request by pietern**
Also see #240.

### CODE REVIEW

**Comment by dougm** [comment]
:+1:

**Comment by mevansam** [comment]
Seems like bool=false is still being omitted.
```
2015/04/13 17:57:05 [DEBUG] ResourceAllocationInfo: &types.ResourceAllocationInfo{
    DynamicData:           types.DynamicData{},
    Reservation:           512,
    ExpandableReservation: &bool(false),
    Limit:                 1024,
    Shares:                &types.SharesInfo{
        DynamicData: types.DynamicData{},
        Shares:      0,
        Level:       "low",
    },
    OverheadLimit: 0,
}
2015/04/13 17:57:05 [DEBUG] ResourceAllocationInfo: &types.ResourceAllocationInfo{
    DynamicData:           types.DynamicData{},
    Reservation:           2048,
    ExpandableReservation: &bool(true),
    Limit:                 3072,
    Shares:                &types.SharesInfo{
        DynamicData: types.DynamicData{},
        Shares:      40960,
        Level:       "custom",
    },
    OverheadLimit: 0,
}
2015/04/13 17:57:05 [DEBUG] VMOMI Request: <Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/"><Body><CreateResourcePool xmlns="urn:vim25"><_this type="ResourcePool">resgroup-112</_this><name>resource_pool1</name><spec><cpuAllocation><reservation>512</reservation><limit>1024</limit><shares><shares>0</shares><level>low</level></shares></cpuAllocation><memoryAllocation><reservation>2048</reservation><expandableReservation>true</expandableReservation><limit>3072</limit><shares><shares>40960</shares><level>custom</level></shares></memoryAllocation></spec></CreateResourcePool></Body></Envelope>
2015/04/13 17:57:05 [DEBUG] VMOMI Response: <Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/"><Body><Fault xmlns="http://schemas.xmlsoap.org/soap/envelope/"><faultcode>ServerFaultCode</faultcode><faultstring>A specified parameter was not correct: </faultstring><detail><Fault></Fault></detail></Fault></Body></Envelope>
```

**Comment by pietern** [comment]
@mevansam Can't tell from your snippet if it is or isn't. The debug lines show a resource pool with the second resource allocation struct being created and returning an error, where the expandable reservation field is set to true.

**Comment by mevansam** [comment]
Sorry the first two lines were from the logs in my terraform plugin. It creates two ResourceAllocationInfo structures one for cpu and another memory and adds them to the ResourceConfigSpec structure passed to ResourcePool.UpdateConfig method. The first one has ExpandableReservation set to false. 

The resulting formatted request created by client.go is below - notice the missing  <expandableReservation> element within the <cpuAllocation> element. I re-ran this with expandableReservation=true for cpu allocation and the test passed.

```
<Envelope
    xmlns="http://schemas.xmlsoap.org/soap/envelope/">
    <Body>
        <CreateResourcePool
            xmlns="urn:vim25">
            <_this type="ResourcePool">resgroup-112</_this>
            <name>resource_pool1</name>
            <spec>
                <cpuAllocation>
                    <reservation>512</reservation>
                    <limit>1024</limit>
                    <shares>
                        <shares>0</shares>
                        <level>low</level>
                    </shares>
                </cpuAllocation>
                <memoryAllocation>
                    <reservation>2048</reservation>
                    <expandableReservation>true</expandableReservation>
                    <limit>3072</limit>
                    <shares>
                        <shares>40960</shares>
                        <level>custom</level>
                    </shares>
                </memoryAllocation>
            </spec>
        </CreateResourcePool>
    </Body>
</Envelope>
```

**Comment by pietern** [comment]
Looking into this.

From the documentation (ResourceAllocationInfo):

> For the methods CreateResourcePool, CreateVApp and ImportVApp, you must provide values for all properties except overheadLimit; they are not optional. (Currently, overheadLimit is for vCenter Server use only.)

**Comment by pietern** [comment]
@mevansam Can you check if #249 solves your issue?

**Comment by mevansam** [comment]
@pietern I verified that #249 fixes this issue. Thanks.

**Comment by pietern** [comment]
@mevansam Thanks, I merged the PR.

**Pull request merged**
