### PR TITLE
Add KMS support to mock vcenter

### PR DESCRIPTION
**Pull request by priyanka19-98**
## Description

Mock VC simulator did not have any support for KMS. 

Added basic KMS support for mock simulator.

Closes: #(issue-number)

## Type of change

Please mark options that are relevant:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update
- [ ] Build related change

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. If applicable, please also list any relevant
details for your test configuration.

- [ ] Test Description 1
- [ ] Test Description 2

## Checklist:

- [ ] My code follows the `CONTRIBUTION` [guidelines] of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

[guidelines]: https://github.com/vmware/govmomi/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by dougm — COMMENTED** [review]
Thanks @priyanka19-98 , this is looking good. Based some things commented out, printfs, main() func in simulator package, etc., is this still work-in-progress? I will take a closer look soon and I've not used KMS at all myself, so want to read up on that a bit too.

**Comment by priyanka19-98** [comment]
> Thanks @priyanka19-98 , this is looking good. Based some things commented out, printfs, main() func in simulator package, etc., is this still work-in-progress? I will take a closer look soon and I've not used KMS at all myself, so want to read up on that a bit too.

yes, I am waiting for one PR to be merged into these changes. Thanks for your response

**Comment by priyanka19-98** [comment]
> > Thanks @priyanka19-98 , this is looking good. Based some things commented out, printfs, main() func in simulator package, etc., is this still work-in-progress? I will take a closer look soon and I've not used KMS at all myself, so want to read up on that a bit too.
> 
> yes, I am waiting for one PR to be merged into these changes. Thanks for your response

@dougm could you please review again?

**Comment by dougm** [comment]
Thanks @priyanka19-98 , will try to review soon. Could you please [rebase](https://github.com/vmware/govmomi/blob/main/CONTRIBUTING.md#updating-pull-requests) ? (note how PR says your branch has "195 commits")

**Comment by dougm** [comment]
#3548 adds simulator support for the CryptoManager related APIs.
@priyanka19-98 have not heard back from you, do you plan on continuing your work on this?
If so, you'll need to rebase. Closing for now.

**Pull request closed without merging**
