### PR TITLE
Add vSAN 7.0 U1 API bindings

### PR DESCRIPTION
**Pull request by gh05tn0va**
The bindings are auto generated from vSAN vMODL definations during esx build.

### CODE REVIEW

**Comment by gh05tn0va** [comment]
note: commit 6454dbd is for 7.0 U1 APIs. The description was mistaken.

**Comment by divyenpatel** [comment]
@gh05tn0va if these bindings are generated automatically we are good. 
but vSphere CSI driver is using CNS bindings and client from https://github.com/vmware/govmomi/tree/master/cns

Auto-generated binding does not have some internal methods and types, but we need them for the vSphere CSI driver.

**Comment by gh05tn0va** [comment]
@divyenpatel The solution is to make these required cns APIs public.
Once this is done, these bindings can be regenerated using latest build.
For now, I think we can tolerate the incomplete cns bindings here.

**Comment by gh05tn0va** [comment]
@divyenpatel what is the status of this review? Would you approve if no other requirements?

**Review by divyenpatel — APPROVED** [review]

**Review by dougm — APPROVED** [review]
Thanks @gh05tn0va

**Pull request merged**
