### PR TITLE
Add support for clusters, hosts and VDS portgroups to govc ls -l

### PR DESCRIPTION
**Pull request by speijnik**
Signed-off-by: Stephan Peijnik <speijnik@anexia-it.com>

### CODE REVIEW

**Comment by speijnik** [comment]
As a side note:

Long output of ls does not show objects for which no "type-case" is present at all.
Wasn't sure if that was intentional or not, but a "default:" case may not hurt there...

**Comment by speijnik** [comment]
Just had another look, this could be further simplified, see https://github.com/anexia-it/govmomi/commit/0ca14af987db2791bb12e2a28546217e63881df6

The rationale behind that approach is that an object reference contains the object type anyways. This means that we can get rid of the switch/case altogether and just use the string from the reference.

**Comment by pietern** [comment]
Thanks for your contribution. Can you please sign and submit our CLA?

Regarding the second commit: looks good. Could you change it to output the trailing / for folder types, as it currently behaves? Thanks!

**Comment by caglar10ur** [comment]
I believe we can close this pull request as https://github.com/vmware/govmomi/commit/40c26fc6eb941aa6853530d4c6d1f2917a92b485 deprecates this.

**Comment by pietern** [comment]
That sounds about right, thanks for noticing @caglar10ur.

**Pull request closed without merging**
