### PR TITLE
Add some common functions to find/finder.go

### PR DESCRIPTION
**Pull request by caglar10ur**
{Datacenter|Datastore|ComputeResource|HostSystem|Network|ResourcePool}OrDefault

They return the requested object or its default value on success or an
error for failure.

### CODE REVIEW

**Comment by pietern** [comment]
What is the intent for these functions?

The behavior seems odd; if I ask for datastore "x" and get datastore "y".

**Comment by caglar10ur** [comment]
This is a common pattern that govmomi consumers repeat all the time so I thought it would be cool to have them. 

For example we have bonneville-common library on top of govmomi to do this and by doing a quick search I see docker-machine is doing the same [1]

[1] https://github.com/docker/machine/blob/master/drivers/vmwarevsphere/vsphere.go#L860

**Comment by pietern** [comment]
The difference between the one in the machine repo and this implementation is that you ignore whatever error happens when looking up the original object and return the default one.

So you can get into a situation where, for example, you ask for datastore "a", while only "b" and "c" exist. The first one returns a not found error and the default implementation will return a "multiple found" error, which is then returned to the user. I would expect this implementation to do the same thing as the function in the machine repo you link so and check whether or not the "path" argument is empty and only use the default implementation if so.

**Comment by caglar10ur** [comment]
Ah, you are right, I missed that case in here. We also do the same (check path argument) so I'll make necessary changes and re-submit.

**Comment by dougm** [comment]
Would be great if we could also change the govc/flags types to use the new helpers.  For example, the DatastoreFlag.Datastore() method.

**Comment by caglar10ur** [comment]
It's not clear to me why travis failed to build this PR. It seems OK locally.

```
[conur@vir://opt/go/src/github.com/vmware/govmomi(master)] git fetch origin +refs/pull/423/merge
From https://github.com/vmware/govmomi
 * branch            refs/pull/423/merge -> FETCH_HEAD
[conur@vir://opt/go/src/github.com/vmware/govmomi(master)] git checkout -qf FETCH_HEAD
[conur@vir://opt/go/src/github.com/vmware/govmomi((HEAD detached at FETCH_HEAD))] go install -v github.com/vmware/govmomi/govc
github.com/vmware/govmomi/find
github.com/vmware/govmomi/govc/flags
github.com/vmware/govmomi/govc/about
github.com/vmware/govmomi/govc/cluster
github.com/vmware/govmomi/govc/datacenter
github.com/vmware/govmomi/govc/datastore
github.com/vmware/govmomi/govc/device
github.com/vmware/govmomi/govc/device/cdrom
github.com/vmware/govmomi/govc/device/floppy
github.com/vmware/govmomi/govc/device/scsi
github.com/vmware/govmomi/govc/device/serial
github.com/vmware/govmomi/govc/dvs
github.com/vmware/govmomi/govc/dvs/portgroup
github.com/vmware/govmomi/govc/events
github.com/vmware/govmomi/govc/extension
github.com/vmware/govmomi/govc/fields
github.com/vmware/govmomi/govc/host
github.com/vmware/govmomi/govc/host/autostart
github.com/vmware/govmomi/govc/host/esxcli
github.com/vmware/govmomi/govc/host/maintenance
github.com/vmware/govmomi/govc/host/portgroup
github.com/vmware/govmomi/govc/host/storage
github.com/vmware/govmomi/govc/host/vnic
github.com/vmware/govmomi/govc/host/vswitch
github.com/vmware/govmomi/govc/importx
github.com/vmware/govmomi/govc/license
github.com/vmware/govmomi/govc/logs
github.com/vmware/govmomi/govc/ls
github.com/vmware/govmomi/govc/permissions
github.com/vmware/govmomi/govc/pool
github.com/vmware/govmomi/govc/vapp
github.com/vmware/govmomi/govc/host/firewall
github.com/vmware/govmomi/govc/version
github.com/vmware/govmomi/govc/vm
github.com/vmware/govmomi/govc/vm/disk
github.com/vmware/govmomi/govc/vm/guest
github.com/vmware/govmomi/govc/vm/network
github.com/vmware/govmomi/govc
[conur@vir://opt/go/src/github.com/vmware/govmomi((HEAD detached at FETCH_HEAD))]
```

**Comment by dougm** [comment]
Thanks @caglar10ur LGTM.  @pietern ?

**Comment by pietern** [comment]
LGTM as well, go for it :)

**Pull request merged**
