### PR TITLE
Add performance manager and govc metric commands

### PR DESCRIPTION
**Pull request by dougm**
* Convert counter IDs to and from stable names, with caching

* Query available metrics, per resource type and interval

* Query N metric samples by name for N resource instances

* Change level per historical interval and per counter

### CODE REVIEW

**Comment by cgtexmex** [comment]
LGTM

From a govc perspective two potential improvements:
- flag for detailed output (including timestamps, etc...I thought json would do that, but I got nothing)
- ability to tail/follow the metric at the specified interval

**Comment by dougm** [comment]
@cgtexmex I meant to include support for -json, I'll do that.

You can get tail with the metric.sample '-n' flag.

I would also like a follow, and something that could generate a graph, but will save that for after this PR.

**Comment by dougm** [comment]
@cgtexmex added the json support and a '-t' flag to metric.sample

**Comment by cgtexmex** [comment]
LGTM -- Thanks!

**Pull request merged**
