### PR TITLE
Support vapp in pool.info command

### PR DESCRIPTION
**Pull request by dougm**
A VirtualApp extends ResourcePool, add '-a' option to pool.info to
support listing vapps.  Remove vapp.info command as it is functionally
the same as pool.info, we can use the vapp.info namespace for something
vapp specific.

Fix pool.info memory status (convert bytes to MB)

### CODE REVIEW

**Comment by dougm** [comment]
cc @caglar10ur

**Comment by caglar10ur** [comment]
:shipit:

**Comment by dougm** [comment]
Thanks @caglar10ur .  Can you review @pietern ?

**Comment by pietern** [comment]
LGTM :+1:

**Pull request merged**
