### PR TITLE
Added Instant Clone feature

### PR DESCRIPTION
**Pull request by brian57860**
Resolves: #1392

### CODE REVIEW

**Comment by brian57860** [comment]
Hello @dougm, I'm just waiting for legal to approve the CLA.

**Comment by brian57860** [comment]
Hello @dougm still waiting on legal, I will resubmit the pull request if necessary when we obtain approval.

**Comment by dougm** [comment]
No need to resubmit @brian57860 , you can leave the pull request open.

**Comment by fehersanyi-bitrise** [comment]
Hello @dougm , Is there a chance that this will be merged soon? 
also, great job implementing it @brian57860

**Comment by dougm** [comment]
@fehersanyi-bitrise we just need a CLA signed by @brian57860 .  Let me know if I can help with anything there @brian57860

**Comment by brian57860** [comment]
Sorry for the delay, but still waiting on legal!

**Comment by fehersanyi-bitrise** [comment]
Hello @brian57860!
Sorry to bother, but is there any progress with legal regarding this PR? 🤔

**Comment by fehersanyi-bitrise** [comment]
Thanks for the quick answer! We hope it will accepted soon! 🙃

**Comment by ghaabor** [comment]
hey @brian57860, do you know about any progress regarding this?

**Comment by akutz** [comment]
Hi @brian57860,

If legal is still blocking for you, would you consider a co-author who has already signed the CLA? If this was resubmitted by such a person, using your original commit, you'd still be on the commit, but we should be able to get this unblocked.

**Comment by akutz** [comment]
Hi @brian57860,

Is there anything we can do to help you unblock this PR? If so, please let us know!

**Comment by XenoPhex** [comment]
Any progress on getting this merged?

**Comment by akutz** [comment]
@dougm CLA is approved, yay! Let's get this merged!

**Review by dougm — APPROVED** [review]
Thank you @brian57860 🎉

**Comment by brian57860** [comment]
Apologies for the delay @dougm but process was totally outside of my control.

**Comment by dougm** [comment]
Understood, no worries on the delay @brian57860 . Thanks again for your contribution!

**Pull request merged**
