### PR TITLE
Automate and update CHANGELOG handling

### PR DESCRIPTION
**Pull request by embano1**
As part of the Github Actions refactoring, the CHANGELOG generation process had to be updated. This PR introduces the following changes:

## Changes

- `CHANGELOG.md` is (**still manually**) created and continuously updated using `./git-chglog -o CHANGELOG.md v0.1.0..${RELEASE}` (provided in a Docker container)
- A (Go-based) templating engine is used (`.chglog`) to drive the layout
  - special commit title prefixes: `govc: <text>` and `vcsim: <text>` are recognized for grouping and highlighting changes
  - all commits are also shown in the `Commits` section for each tag
  - SemVer is consistently used
- To catch regressions, a pseudo `RELEASE_CHANGELOG` is generated in each build workflow (PRs, etc.)
- Release process is documented, incl. notes on **how to update** the `CHANGELOG.md` after each successful release
  - `goreleaser` will push a **tag-specific** CHANGELOG (same template) to [release](https://github.com/vmware/govmomi/releases) 
  - Each release section can be further edited since it's all based on Markdown
- Documentation cleanup, e.g. only one `CHANGELOG.md` in the root of the repo is kept
  - The original `CHANGELOG.md` has been updated using the new template
- Minor documentation changes towards more standardization, e.g. code blocks and syntax highlighting

## Example snippet for the current v0.25.0 release:

<a name="v0.25.0"></a>
## [Release v0.25.0](https://github.com/vmware/govmomi/compare/v0.24.1...v0.25.0)

> Release Date: 2021-04-16

### 💫 `govc` (CLI)

- add vm.customize -dns-suffix flag
- update test images URL
- log invalid NetworkMapping.Name with import.ova command
- revert pretty print pruning optimization
- add library.update command
- add session.ls -S flag
- add tree command
- include sub task fault messages on failure
- remove device.boot -firmware default
- add '-trace' and '-verbose' flags

### 💫 `vcsim` (Simulator)

- put verbose logging behind '-trace' flag
- add moid value mapping mappings
- add vsan simulator

### 📖 Commits

- Fix folder write for govc container [6fe8d60a]
- docs: update for 0.25 release [e18b601f]
- govc: add vm.customize -dns-suffix flag [1ac314c3]
- Add Cron Docker Login Action [22d911f6]
- govc: update test images URL [60e0e895]
- Add action to automate release [3385b3e0]

Closes: #2369

### CODE REVIEW

**Review by dougm — COMMENTED** [review]
Awesome, but is there a chglog release binary or container image we can use, instead of vendoring all of its sources and deps?

**Comment by embano1** [comment]
> Awesome, but is there a chglog release binary or container image we can use, instead of vendoring all of its sources and deps?

Yes, we could use this Docker SHA https://quay.io/repository/git-chglog/git-chglog/manifest/sha256:998e89dab8dd8284cfff5f8cfb9e9af41fe3fcd4671f2e86a180e453c20959e3

**Comment by embano1** [comment]
@dougm made the changes (using Docker now), ready for review.

**Review by dougm — APPROVED** [review]
Most excellent, thank you @embano1 !!

**Comment by embano1** [comment]
Appreciate it, Doug!

**Pull request merged**
