### PR TITLE
Adding the RegisterVM task.

### PR DESCRIPTION
**Pull request by daniellockard**

### CODE REVIEW

**Comment by dougm** [comment]
@daniellockard looks great, thanks!

Can you submit a CLA if you haven't already?  See: https://github.com/vmware/govmomi/wiki#contributing

**Comment by daniellockard** [comment]
@dougm I'm working on pushing that through legal right now :)

**Comment by daniellockard** [comment]
@dougm I just submitted my CLA.

**Comment by dougm** [comment]
@daniellockard awesome, thanks again.

**Pull request merged**
