### PR TITLE
Added dvs.portgroup.info command to query for distributed portgroup ports using criteria from arguments

### PR DESCRIPTION
**Pull request by eyz**
Arguments:

- -active (Filter by port active or inactive status)
- -connected (Filter by port connected or disconnected status)
- -count (Number of matches to return; 0 = unlimited)
- -dvpg (Distributed Virtual Portgroup inventory path)
- -dvs (Distributed Virtual Switch inventory path; required)
- -inside (Filter by port inside or outside status)
- -vlanId (Filter by VLAN ID; 0 = unfiltered)

### CODE REVIEW

**Comment by eyz** [comment]
I have implemented some of this logic in a new set of NetworkFlag arguments, as of PR #473, but this dvs.portgroup.info allows for more complex queries, thus it is likely still useful

**Comment by eyz** [comment]
Merged vmware/govmomi master to eyz/govmomi branches

**Comment by eyz** [comment]
@dougm: Looks like the drone build failed, but if you find my PR is somehow responsible please let me know how I can assist

**Comment by dougm** [comment]
@eyz thanks, see #481 and let me know if that looks good to you.  We should also be using OutputFlag / tabwriter instead of fmt.Printf, but that change can be done later.

**Comment by eyz** [comment]
Closing this PR, in lieu of cleanup and build fix @dougm in #481

**Pull request closed without merging**
