### PR TITLE
fix: toolbox: add freebsd stub for fileExtendedInfoFormat

### LINKED ISSUE #3620: [BUG] 'make test' is failing using FreeBSD Ports sysutils/govmomi
**Describe the bug**
'make test' is failing when using FreeBSD Ports. 

Error messages in the log are:
```
...
# github.com/vmware/govmomi/toolbox
toolbox/command.go:535:19: undefined: fileExtendedInfoFormat
toolbox/command.go:646:16: undefined: fileExtendedInfoFormat
FAIL    github.com/vmware/govmomi/toolbox [build failed]
FAIL    github.com/vmware/govmomi/toolbox/toolbox [build failed]
...
=== RUN   TestFileInfo
    guest_operations_manager_test.go:48: exit status 1
--- FAIL: TestFileInfo (0.00s)
...
--- FAIL: TestProcessCommand (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
...
```

**To Reproduce**

1. cd sysutils/govmomi
2. make test

**Expected behavior**
Expecting tests are PASSed.

**Affected version**
Tested on 0.46.0.

**Screenshots/Debug Output**
Execution log is attached in [govmomi-test-0.46.0.txt](https://github.com/user-attachments/files/17690596/govmomi-test-0.46.0.txt)

**Additional context**
[govmomi-test-0.46.0.txt](https://github.com/user-attachments/files/17690596/govmomi-test-0.46.0.txt)

### PR DESCRIPTION
**Pull request by dougm**
Fixes #3620

### CODE REVIEW

**Comment by dougm** [comment]
@asxe can you try with these changes? I'm not setup with a freebsd system currently.

**Comment by asxe** [comment]
Looks good, TestProcessCommand is skipped. But next TestProcessKill is failing with the same error. Shall it be another PR?

=== RUN   TestProcessCommand
    process_test.go:86: exec: "/bin/bash": stat /bin/bash: no such file or directory
--- SKIP: TestProcessCommand (0.00s)
=== RUN   TestProcessKill
    process_test.go:155: exec: "/bin/bash": stat /bin/bash: no such file or directory
--- FAIL: TestProcessKill (0.00s)

**Comment by asxe** [comment]
@dougm,
Also, TestProcessIO is failing with 'exec: no command'. Probably, the same /bin/bash dependency.

=== RUN   TestProcessIO
    process_test.go:250: exec: no command
--- FAIL: TestProcessIO (0.00s)

**Comment by asxe** [comment]
all the places where "/bin/bash" hardcoded and not skipped.
Bash is available on FreeBSD as /usr/local/bin/bash if installed.

work/github.com/vmware/govmomi@v0.46.0/guest/toolbox/client.go
work/github.com/vmware/govmomi@v0.46.0/toolbox/process/process_test.go:

**Comment by dougm** [comment]
Thanks for testing @asxe , let's use this same PR to get all the tests passing on FreeBSD. Updated to just skip the toolbox/process tests unless OS is linux or darwin. Not expecting this package to get used elsewhere anyhow.
Please update if you're able to try the current branch, would like to get tests passing on FreeBSD before the next govmomi release.

**Review by akutz — APPROVED** [review]
Thanks @dougm !

**Pull request merged**
