### PR TITLE
Add info about maintenance mode in host.info

### PR DESCRIPTION
**Pull request by Akasurde**
Fix adds information about host's maintenance mode in
host.info command.

Fixes: #771

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

### CODE REVIEW

**Comment by Akasurde** [comment]
cc @dougm

**Comment by dougm** [comment]
@Akasurde how about wemake it "State" instead and have it behave as the GUI does:

```
if inMaintMode {
   println "State: Maintenance Mode"
} else {
   // HostSystemConnectionState (connected,notResponding,disconnected)
   println "State: $runtime.connectionState" 
}
```

**Comment by dougm** [comment]
@Akasurde :+1:

**Comment by Akasurde** [comment]
Thanks @dougm

**Pull request merged**
