### PR TITLE
change for looking up a VM using instanceUUID

### PR DESCRIPTION
**Pull request by abathla**
Added bool flag instanceUUID to find a VM with instanceUUID if set to true.

### CODE REVIEW

**Comment by pietern** [comment]
@dougm What do you think?

**Comment by dougm** [comment]
:+1: Guessing this wrapper method started as a copy-n-paste of the FindByIp wrapper and simply missed adding the additional param.

**Comment by pietern** [comment]
@abathla Any reason in particular to use a `*bool` instead of a value?

**Comment by abathla** [comment]
@pietern no, just that type definition of FindByUuidRequest had *bool in it.

**Comment by abathla** [comment]
@pietern If I change the definition to type, then I make it mandatory for all the calls to pass it, since its a optional value, that didn't seem right to me. At the same time passing false instead of null doesn't hurt much if change it to type.

**Comment by pietern** [comment]
Sounds good, thanks for the clarification!

**Pull request merged**
