### PR TITLE
Add virtualmachine clone to govc

### PR DESCRIPTION
**Pull request by cblomart**
Basic clone functionalities:
  - clone to(/from) template
  - clone to datastore or storagepod
  - folder and resourcepool support

Ability to:
  - poweron 
  - change cpu or memory
  - cutomize via named customization spec
  - waitfor ip (if powering on)

### CODE REVIEW

**Comment by cblomart** [comment]
```
not ok 86 vm.clone
# (from function `flunk' in file govc/test/test_helper.bash, line 165,
#  from function `assert_success' in file govc/test/test_helper.bash, line 170,
#  in test file govc/test/vm.bats, line 409)
#   `assert_success' failed
# command failed with exit status 1: govc: The operation is not supported on the object.
```
clone not supported on standalone esxi?

**Comment by cblomart** [comment]
defenitively no clone without vcenter

**Comment by cblomart** [comment]
This would help issue #407

**Comment by dougm** [comment]
Looks great, thanks @cblomart !

**Comment by coxley** [comment]
Was the documentation updated to reflect these additions? Just not in the PR

**Comment by cblomart** [comment]
no, on it.

2016-04-10 3:00 GMT+02:00 Codey Oxley <notifications@github.com>:

**Comment by dougm** [comment]
We don't currently have a govc doc other than the embedded help.  You can implement the `HasUsage` and `HasDescription` interfaces to add more detail for a command.  For example, in govc/dvs/create.go

```go
func (cmd *create) Usage() string {
	return "DVS"
}

func (cmd *create) Description() string {
	return `Create DVS (DistributedVirtualSwitch) in datacenter.

The dvs is added to the folder specified by the 'parent' flag. If not given,
this defaults to the network folder in the specified or default datacenter.`
}
```

**Comment by hoshposh** [comment]
@cblomart : Any chance you can provide an example of how to clone a template or existing VM, along with customizations?

A wiki page would be great, or a pointer to gist that you know of.

Cheers!

**Comment by murarisumit** [comment]
@cblomart: Is it possible to attach a static ip to host while cloning it ?

**Pull request merged**
