### PR TITLE
govc: fix tasks to activate option dump/json/xml

### PR DESCRIPTION
**Pull request by Syuparn**
## Description

This PR fixes `govc tasks` command to handle command options `-dump`, `-json`, and `-xml` as the help explains.

Closes: #2582

## Type of change

Please mark options that are relevant:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. If applicable, please also list any relevant
details for your test configuration.

- [x] `govc tasks -dump` prints dumped struct

```bash
$ ./govc tasks -dump -n 1
types.TaskInfo{
    Key:           "task-64",
    Task:          types.ManagedObjectReference{Type:"Task", Value:"task-64"},
    Description:   (*types.LocalizableMessage)(nil),
    Name:          "PowerOn",
    DescriptionId: "VirtualMachine.powerOn",
    Entity:        &types.ManagedObjectReference{Type:"VirtualMachine", Value:"vm-63"},
    EntityName:    "vm-63",
    Locked:        nil,
    State:         "success",
    Cancelled:     false,
    Cancelable:    false,
    Error:         (*types.LocalizedMethodFault)(nil),
    Result:        nil,
    Progress:      0,
    Reason:        &types.TaskReasonUser{
        TaskReason: types.TaskReason{},
        UserName:   "vcsim",
    },
    QueueTime:     time.Now(),
    StartTime:     types.NewTime(time.Now()),
    CompleteTime:  types.NewTime(time.Now()),
    EventChainId:  0,
    ChangeTag:     "",
    ParentTaskKey: "",
    RootTaskKey:   "",
    ActivationId:  "",
}
```

- [x] `govc tasks -json` prints JSON

```bash
$ ./govc tasks -json -n 1
{
  "Tasks": [
    {
      "Key": "task-64",
      "Task": {
        "Type": "Task",
        "Value": "task-64"
      },
      "Description": null,
      "Name": "PowerOn",
      "DescriptionId": "VirtualMachine.powerOn",
      "Entity": {
        "Type": "VirtualMachine",
        "Value": "vm-63"
      },
      "EntityName": "vm-63",
      "Locked": null,
      "State": "success",
      "Cancelled": false,
      "Cancelable": false,
      "Error": null,
      "Result": null,
      "Progress": 0,
      "Reason": {
        "UserName": "vcsim"
      },
      "QueueTime": "2021-09-12T14:34:54.392921363+09:00",
      "StartTime": "2021-09-12T14:34:54.392940196+09:00",
      "CompleteTime": "2021-09-12T14:34:54.393230612+09:00",
      "EventChainId": 0,
      "ChangeTag": "",
      "ParentTaskKey": "",
      "RootTaskKey": "",
      "ActivationId": ""
    }
  ]
}
```

- [x] `govc tasks -xml` prints XML

```bash
$ ./govc tasks -xml -n 1
<TaskInfo>
  <key>task-64</key>
  <task type="Task">task-64</task>
  <name>PowerOn</name>
  <descriptionId>VirtualMachine.powerOn</descriptionId>
  <entity type="VirtualMachine">vm-63</entity>
  <entityName>vm-63</entityName>
  <state>success</state>
  <cancelled>false</cancelled>
  <cancelable>false</cancelable>
  <reason xmlns:XMLSchema-instance="http://www.w3.org/2001/XMLSchema-instance" XMLSchema-instance:type="TaskReasonUser">
    <userName>vcsim</userName>
  </reason>
  <queueTime>2021-09-12T14:34:54.392921363+09:00</queueTime>
  <startTime>2021-09-12T14:34:54.392940196+09:00</startTime>
  <completeTime>2021-09-12T14:34:54.393230612+09:00</completeTime>
  <eventChainId>0</eventChainId>
</TaskInfo>
```

- [x] `govc tasks` prints plain string same as before

```bash
$ ./govc tasks -n 1
Task                                     Target                         Initiator                         Queued   Started Completed Result
PowerOn                                  vm-63                          vcsim                           14:34:54  14:34:54  14:34:54 success [290.416µs]
```

- [x] `govc tasks -f` prints plain string and waits for new tasks
  - run `govc vm.power -off /DC0/vm/DC0_C0_RP0_VM0` on another window and the poweroff task is shown

```bash
$ ./govc tasks -f
...
PowerOn                                  vm-63                          vcsim                           14:34:54  14:34:54  14:34:54 success [290.416µs]
PowerOff                                 vm-60                          vcsim                           14:38:22  14:38:22  14:38:22 success [338.08µs]
```

**Test Configuration**:
* vCenter: vcsim 0.26.1

## Checklist:

- [x] My code follows the CONTRIBUTION [guidelines](./../CONTRIBUTING.md) of
  this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Comment by Syuparn** [comment]
I found this PR deals with the same thing as #2385, which is pending for CLA. If the PR is preferred to this, I will fork it and make another PR (as its contributer suggests) instead.

**Comment by embano1** [comment]
Let's see what @breunigs says, but perhaps an option would be to attribute him via https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors#further-reading?

Not sure if the CLA bot also complains about co-authors, but pretty sure it should work if you submit the PR/commit.

**Comment by Syuparn** [comment]
@embano1

Thank you for reply and suggestion. I will ask @breunigs his PR and if I could be a co-author.

(I missed the point of the comment (cloning PR by his company members), so the situation is a little different.)

**Review by dougm — APPROVED** [review]
Thank you @Syuparn and @breunigs , I tried it out just now with the format flags and it looks great!

**Comment by Syuparn** [comment]
@embano1, @dougm, and @breunigs

Thank you so much for reviews and your advice!

**Pull request merged**
