### PR TITLE
Add support for golangci-lint

### PR DESCRIPTION
**Pull request by akutz**
## Description

This patch introduces support for golangci-lint, the de facto linter for Golang code. This patch replaces the former goimports and govet targets in the Makefile with the lint target. Please note the old, check target is still present for backwards compatability.
    
The golangci-lint binary is obtained automatically by using the new hack/tools directory pattern. The directory hack/tooks is a Go sub-module, github.com/vmware/govmomi-tools, which allows it to have its own go.mod and go.sum files. This way the module can be used to maintain a list of Go-based tooling for the project without impacting the actual dependencies in the root Go module.

Closes: _NA_

## Type of change

Please mark options that are relevant:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update
- [x] Project management related

## How Has This Been Tested?

By running the following commands locally:

* `make install`
* `make check`
* `make lint`
* `make fix`

## Checklist:

- [x] My code follows the CONTRIBUTION [guidelines](./../CONTRIBUTING.md) of
  this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~
- [ ] ~~New and existing unit tests pass locally with my changes~~
- [x] Any dependent changes have been merged (this PR depends on #2453)

### CODE REVIEW

**Comment by embano1** [comment]
Did the changes from the vendor PR also got in here? Also, looks like the lint target is not run via action and the old linters are still used (see lint workflow).

**Comment by akutz** [comment]
> Did the changes from the vendor PR also got in here? Also, looks like the lint target is not run via action and the old linters are still used (see lint workflow).

Yes, they are here. As the description says, this PR depends on the vendor PR. I will rebase when that is merged.

**Comment by embano1** [comment]
I might be blind but did not see that description/note here, this was asking. Thx for clarification :)

**Comment by akutz** [comment]
> Update: found it (read over it bc the checkbox was not checked 😂)

Ha!

**Review by dougm — DISMISSED** [review]
Thanks @akutz , lgtm

**Comment by embano1** [comment]
@akutz should we also reflect these changes in the CI workflows?

**Comment by akutz** [comment]
I mean, probably? :)

I will update with those. Need to rebase onto non-vendored main anyway.

**Comment by embano1** [comment]
Great, so we have consistency across the workflows and local environments by both using the new Makefile targets.

**Comment by akutz** [comment]
Okay @embano1 , it is updated. Doing so removed the approval from @dougm, so if you or he could approve, I'd appreciate it!

**Review by dougm — APPROVED** [review]
lgtm

**Pull request merged**
