### PR TITLE
Add vm.console command

### LINKED ISSUE #833: Add support to generate VMRC link
Hi,

in the vSphere Web Client (v5.5.0) you have the option to open a VM in VMWare Remote Console (VMRC) via an application link (e.g. `vmrc://clone:LONGSTRING@VCENTER:443/?params`).
It would be totally awesome if we could generate such a link via govmomi/govc.

Is this feature possible to implement?

### PR DESCRIPTION
**Pull request by dougm**
Fixes #833

### CODE REVIEW

**Comment by dougm** [comment]
Example vmrc URL output:

```console
% govc vm.console dougm-toolbox-test
vmrc://clone:cst-5259a8e8-fd70-5217-96b1-96cb4590e798--tp-BA-CC-4B-71-30-0E-1E-30-41-DF-94-B6-07-E4-9C-AA-FA-63-8C-A0@192.168.2.128/?moid=145
```

**Comment by dougm** [comment]
@T4cC0re can you take a look (at the "Examples:" section at least), is this what you had in mind?

**Comment by T4cC0re** [comment]
Hey @dougm, thanks for your help!  
This is exactly what I had in mind. I already took your fork and tested it in our vCenter. Purrs like a kitten!

**Comment by dougm** [comment]
@T4cC0re great, thanks for the suggestion and testing the PR!

**Pull request merged**
