### PR TITLE
vcsim: Add RUN.port.xx flag to publish ports on container backed VM

### PR DESCRIPTION
**Pull request by BrianMMcClain**
## Description

Hey there! As usual, just wanted to put this out there for consideration, but for my user case I found it would be useful to publish ports on container-backed VMs. In my particular case, my use case was that I needed to SSH into the running Docker container and I was struggling with using the local container networking directly. 

I'm not sure if this is the most ideal implementation, but this change looks for a configuration key in the format of `RUN.port.xx` and expects a value to publish the port on. For example, `RUN.port.22 = 2222` will publish port 22 in the container on port 2222 of the host.

If you don't think this is a good addition, feel free to close :) Thanks!

## Type of change

Please mark options that are relevant:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update
- [ ] Build related change

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. If applicable, please also list any relevant
details for your test configuration.

- govc vm.power -off DC0_H0_VM0
- govc vm.change -vm DC0_H0_VM0 -e RUN.container=nginx
- govc vm.change -vm DC0_H0_VM0 -e RUN.port.80=8888
- govc vm.power -on DC0_H0_VM0
- curl 127.0.0.1:8888

## Checklist:

- [x] My code follows the `CONTRIBUTION`
  [guidelines](https://github.com/vmware/govmomi/blob/main/CONTRIBUTING.md) of
  this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Review by dougm — APPROVED** [review]
@BrianMMcClain thanks, lgtm. Sorry, I merged your other PR before reviewing this and there's a merge conflict that needs to be resolved, can you take a look?

**Comment by BrianMMcClain** [comment]
Hey @dougm, no problem at all! I resolved the merge conflict, though I'm seeing that now the `ExampleHandlerREST` test is failing and I'm not totally sure why? I'm unable to reproduce locally, but it looks like perhaps in the test, the session isn't expiring as expected? Not totally sure if that's related to the code I added, or perhaps a weird hiccup on the GH Action? Either way, figured I'd see what you think since I can't really nail down what might cause that 😅 Thanks!

**Comment by BrianMMcClain** [comment]
@dougm Sorry about that! Totally missed that part in the contribution guide. I've updated the branch to rebase off main and squash the commits. Let me know if there's anything else I can do :) Thanks!

**Review by dougm — APPROVED** [review]
Thanks @BrianMMcClain !
Multiple commits in a PR is fine, its just the fixup changes we want to squash before merging.

**Pull request merged**
