### PR TITLE
Add FindByUuid method for Virtual Machine

### PR DESCRIPTION
**Pull request by Akasurde**
Fix adds method to search Virtual Machine using UUID

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

### CODE REVIEW

**Comment by dougm** [comment]
thanks @Akasurde , any issues with signing the CLA?

**Comment by Akasurde** [comment]
@dougm Nope.

**Comment by dougm** [comment]
:+1:

**Comment by Akasurde** [comment]
@dougm Thanks for review and merge.

**Pull request merged**
