### PR TITLE
govc: improved vm.clone for templates

### LINKED ISSUE #1900: govc template.clone action wanted
vSphere 6.7 supports cloning a template to template, which is useful for example when you want to move templates around.

I tested `vm.clone` action as a replacement, however it didn't work - at first vSphere proceeded with cloning, hower later GOVC tried to power this template up and it failed.

```
govc vm.clone -pool=packer-templates \
  -ds=new-datastore -template=true -cluster=cluster1 \
  -vm templates/ubuntu-18.04-264490 templates/cloned-ubuntu-18.04-264490 
```

As a user, I'd love to have gcov support 'template.clone' action with similar syntax to 'vm.clone' so I can safely copy files across with CLI.

### PR DESCRIPTION
**Pull request by weakcamel**
* skip starting the VM when -template flag is selected
* update documentation to include template clone example

resolves  #1900

### CODE REVIEW

**Comment by weakcamel** [comment]
@dougm My pleasure and besides, you actually solved it, I just wrapped it up :-)

It seems that one of the integration tests failed at https://travis-ci.org/github/vmware/govmomi/jobs/672021697  but since it's got nothing to do with my change, it might be just a bit flappy?

```
--- FAIL: TestKeepAlive (0.11s)

    keep_alive_test.go:97: Expected i != 0, got i: {0}

    testing.go:853: race detected during execution of test

=== RUN   TestRealKeepAlive

--- SKIP: TestRealKeepAlive (0.00s)

=== RUN   TestKeepAliveHandler

--- PASS: TestKeepAliveHandler (2.14s)

    keep_alive_test.go:222: failed to re-authenticate, quitting keep alive handler

FAIL

FAIL	github.com/vmware/govmomi/session	2.278s
```

**Comment by dougm** [comment]
@weakcamel sure I helped, but making the PR and testing against real vCenter is often more than half the battle, so I appreciate your contribution!

That test is indeed flaky and unrelated to your change.  We just need CLA bot to approve before merging, were you able to sign the CLA?

**Comment by weakcamel** [comment]
@dougm Thanks for reply; phew, I'll not worry about this test result.

And yes, I signed the CLA yesterday. Testing against vCenter also went well, template got succesfully cloned.

**Comment by weakcamel** [comment]
I did observe an unexpected behaviour though. 

When running the sample command from https://github.com/vmware/govmomi/issues/1900, the selected datastore (`-ds`) was not honoured and another one (another NFS datastore on my vCenter, not being part of a datastore cluster) was selected to clone the template to, e.g.

```
govc vm.clone -pool=packer-templates \
  -ds=other-datastore -template=true -cluster=cluster1 \
  -vm templates/ubuntu-18.04-264490 templates/cloned-ubuntu-18.04-264490 
```

My Golang knowledge is basic to say the least, however I managed to run `govc` under gdb and 
it seems to be using the Datastore from recommendations and not the one selected with `-ds` flag - it hits this breakpoint: https://github.com/weakcamel/govmomi/blob/6c68ccf222bc08a8450c0b2049ea420852100f35/govc/vm/clone.go#L420

Is this the expected behavior? When doing the same operation from UI, my selection of datastore was preserved.

**Comment by dougm** [comment]
@weakcamel yeah, the `-cluster` flag takes precedence over the `-ds` flag in govc (via PlaceVm).  You can workaround that by using `-pool cluster1/Resources` instead of `-cluster cluster1`.

**Pull request merged**
