### PR TITLE
fix: Allow go 1.17 to go install

### PR DESCRIPTION
**Pull request by smaftoul**
## Description

Go.mod contains two replace directives. This commit moves the replaced packages directly in the required.
It allows to `go install github.com/vmare/govmomi/govc@latest` with go 1.17.

Otherwise we get:

```
go install github.com/vmware/govmomi/govc@latest
go install: github.com/vmware/govmomi/govc@latest (in github.com/vmware/govmomi@v0.27.3):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

## Type of change

Please mark options that are relevant:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update
- [x] Build related change

### CODE REVIEW

**Comment by embano1** [comment]
@smaftoul did you already sign the CLA?

**Comment by embano1** [comment]
Not sure why that comment is still there then. I see your commit is not signed off though, could you please do so (use `-s` with the same Github author email used when signing the CLA). Thx

**Review by embano1 — APPROVED** [review]
LGTM

**Comment by smaftoul** [comment]
@embano1 thanks for merging, I was about to signoff the commit ;)

**Comment by embano1** [comment]
All good, didn't want to hold further after checking that you are already in the CLA list.

**Comment by sodul** [comment]
@smaftoul @embano1 does this fix #2345 ?

**Pull request merged**
