### PR TITLE
Update finder.go / func VirtualMachineList

### PR DESCRIPTION
**Pull request by sszgr**
In the functions of VirtualMachineList, e.Object.(type) may be mo.Folder, and exist VirtualMachine under the Folder.
Add function findVirtualMachineListForFolder, which is change to foreach all Folder. But I didn't get VirtualMachine.InventoryPath.
Sorry for my bad code, hope someone could help me to improve it.

### CODE REVIEW

**Comment by pietern** [comment]
Hi @sszgr, thank you for your contribution. If I read your code correctly, you're trying to recurse into a folder and list the virtual machines there if you see a folder? I.e. you want to walk the entire tree and return all VMs in all folders?

The function currently lets you specify the path you want to get a listing for. This means that if there is a folder you want to recurse into, you can specify so in the path. If you want to recurse into every folder, you can specify the path using a wildcard, like so: `/mydc/vms/*`. This will expand to every entry in this folder, including the folders, and will list the contents for every single entry (being VMs and folders).

For building something that recurses I would rather have an interface like this: http://godoc.org/path/filepath#Walk and implement it for any managed object rather than just VMs.

By the way, I see you opened and closed a number of pull requests. Please update an existing pull request instead of creating a new one for every change. Also see: https://help.github.com/articles/changing-a-commit-message/

**Comment by sszgr** [comment]
Hi @pietern, thank you for your reply!
I found that ```f.find(ctx, f.vmFolder, false, "/myDC/vm/*")``` had just list the folders under current folder without recursion. and ```f.find(ctx, f.vmFolder, true, "/myDC/vm/*")``` just list more folders under the child folders which are under current folder without recursion.
As well as in ```func(f*Finder) VirtualMachineList()``` had also not traversal folder, it just case ```mo.VirtualMachine```.
Maybe I get the wrong comprehension, I thought that ```func VirtualMachineList``` should list all VirtualMachine under the path by using recursion. I would feel pity if it can just only list current VirtualMachine  without traversal, ignore this.
By the way, I will follow your suggest, read git help carefully.
Thank you.

**Comment by dougm** [comment]
Issue #190

**Comment by sszgr** [comment]
Thank you very much.

**Comment by austinlparker** [comment]
@sszgr if you're still around, I could really use this PR. if you're no longer interested in it I'll resubmit your change.

**Comment by sszgr** [comment]
sorry for reply  your email so late , thank you very much.

**Comment by sszgr** [comment]
@vmwclabot thanks.

**Comment by avnish30jn** [comment]
@pietern `/mydc/vms/*` this doesn't recurse into the folder.

**Pull request closed without merging**
