### PR TITLE
vendor golang.org/x/net/context

### PR DESCRIPTION
**Pull request by caglar10ur**

### CODE REVIEW

**Comment by dougm** [comment]
Thanks @caglar10ur .  Looks like we'd still need to go install goimports for CI to be happy?

**Comment by caglar10ur** [comment]
amended last commit to do ```go install ./vendor/golang.org/x/tools/cmd/goimports```

**Comment by dougm** [comment]
@caglar10ur on second thought, after seeing the 10k line golang.org/x/tools/imports/zstdlib.go - how about if we just vendor the packages needed to compile (context and go-spew).  I think it'd still be ok to use 'go get' for goimports in CI.

**Comment by caglar10ur** [comment]
Dropped goimports

**Pull request merged**
