### PR TITLE
include GOVC_USERNAME and GOVC_PASSWORD in govc README

### PR DESCRIPTION
**Pull request by kikitux**

### CODE REVIEW

**Comment by kikitux** [comment]
Related to issue https://github.com/vmware/govmomi/issues/273

**Comment by pietern** [comment]
Thanks for the PR, good idea to include it in the readme.

Can you please sign and submit the CLA? (see [this wiki page](https://github.com/vmware/govmomi/wiki#contributing)).

**Comment by kikitux** [comment]
@pietern Done it, sent by email.

**Comment by pietern** [comment]
Thank you!

**Pull request merged**
