### PR TITLE
Datastore clusters

### PR DESCRIPTION
**Pull request by pietern**
Not finished yet, making PR so progress can be tracked.

### CODE REVIEW

**Comment by pietern** [comment]
@dougm This is good to go. Can you take a look?

**Comment by dougm** [comment]
Very nice, LGTM!  ChangeLog update would be good too :)

**Comment by pietern** [comment]
Amending the last commit to include it in the changelog :)

**Comment by pietern** [comment]
@dougm FYI, also updated the disk argument help to vm.create: 

https://github.com/pietern/govmomi/commit/bfe414fe43430bd101e6bddd7fdff419063ebe58#diff-b031c504656e40a4019b56995c6b86c7R110

**Comment by dougm** [comment]
:+1: :shipit:

**Pull request merged**
