### PR TITLE
added SessionIsActive to Client

### PR DESCRIPTION
**Pull request by cgtexmex**
Simple addition to client implementing the SessionIsActive method

### CODE REVIEW

**Comment by dougm** [comment]
Thanks @cgtexmex , LGTM.  @pietern - is it time for a SessionManager wrapper or are you ok having these methods attached to the Client type?

**Comment by pietern** [comment]
@dougm I agree. It should also implement an interface that can help us taking care of #224.

**Comment by cgtexmex** [comment]
I viewed the client as the govmomi equivalent of the session manager -- I guess it more aligns to the ServiceInstance.  I'd be happy to help with the implementation of a SessionManager wrapper, etc...

**Comment by dougm** [comment]
@cgtexmex great, have a look at the existing govmomi/*_manager.go wrappers.  Each has a corresponding govmomi.Client.*Manager() getter.  So in this case we'd end up with govmomi/session_manager.go and a Client.SessionManager() SessionManager() method.

We have been talking about moving these wrappers into their own packages.  So this could be govmomi/session/manager.go and govmomi.Client.SessionManager() would return type session.Manager - thoughts @pietern ?

**Comment by pietern** [comment]
@dougm Sounds good. The end goal being that we have bits and pieces of reusable functionality that you can pick and choose from and only depend on the vim25 packages.

**Comment by cgtexmex** [comment]
I am working this -- I'll handle it in two PRs -- first will be the basic session package creation with the Manager.  That will contain the SessionIsActive method.  Then I'll have the next PR address Issue #224.

**Comment by pietern** [comment]
@cgtexmex Sounds good. How do you plan to address #224? One idea is through implementing the soap.RoundTripper on top of the session manager, such that it can intercept failed requests and reauthenticate if necessary. Another idea is to have it live on the side but asynchronously run ping requests to keep the session alive. I'd like some discussion around this before proceeding.

@dougm What do you think?

**Comment by cgtexmex** [comment]
@pietern I've not given it a lot of thought as of yet...I'll be sure to ping you and @dougm when I've got a solid direction.

**Comment by pietern** [comment]
@cgtexmex Thanks.

**Comment by dougm** [comment]
If we have a goroutine on the side keeping the session alive, then we would defeat any attempt to Client.Transport.(*http.Transport).CloseIdleConnections() - unless we add a wrapper method that will stop the ping goroutine and then call CloseIdleConnections.  Otherwise, it seems reasonable and rvc takes a similar approach: https://github.com/vmware/rvc/blob/master/lib/rvc/modules/vim.rb#L126-L131

If we can re-authenticate as needed in 1 place within the RoundTripper impl and keep it simple, that would probably be better.

**Comment by pietern** [comment]
Agree that one place to do this very predictibly is the better solution here.

We can make soap.RoundTripper our abstraction and have the session manager implement this interface. Then we'll have an "AuthenticatingRoundTripper" of sorts, that takes care of authentication as needed, plus an explicit authentication function that can be called by govmomi.NewClient.

**Comment by cgtexmex** [comment]
I've create a session manager wrapper and moved the login / logout functionality to that wrapper.  I've also added a SessionManager type to the Client Struct.  This allows the Client to perform the login / logout.  Other SessionManager specific methods (SessionIsActive) would require the user to grab the Session from Client and execute the method.  

If you are happy with this then I'll look at the addressing #224 in a new PR

**Comment by dougm** [comment]
@cgtexmex looks great, thanks!

**Pull request merged**
