### PR TITLE
Add device.usb.add command

### LINKED ISSUE #569: govm vm.change to add a USB controller
I can't find a way to add a USB controller to a new VM, either with `vm.create` or `vm.change`.

The source suggests this isn't implemented yet?

```
$ git grep -c -E 'usb|USB|Usb' 
vim25/types/enum.go:28
vim25/types/types.go:41
```

... only the auto-generated code mentions USB.

I can create OS X VMs with vm.create, but then I can't move the mouse around in them, since they lack USB.

If I create VMs with the web UI, then I can add a USB controller and move the mouse & type and such.

### PR DESCRIPTION
**Pull request by dougm**
Supports adding USB controllers to VMs.

Fixes #569

### CODE REVIEW

**Comment by dougm** [comment]
Haven't tested yet other than the change to device.bats, but something along these lines should do the trick @bradfitz

**Comment by bradfitz** [comment]
Thanks! Looks perfect. I'll try this out today.

**Comment by caglar10ur** [comment]
LGTM

**Comment by bradfitz** [comment]
And I confirm it worked for me.

I now have new problems, but that's good. :-)

Thanks again.

**Pull request merged**
