### PR TITLE
Fixed docs for govc library.info w/-json

### PR DESCRIPTION
**Pull request by mikeschinkel**
Fixed docs for govc library.info w/-json

When -json comes after the "library/item" then it does not trigger JSON output.

### CODE REVIEW

**Review by embano1 — APPROVED** [review]
LGTM

**Comment by embano1** [comment]
Thx for the contribution.
If not already done so, please sign the CLA so we can merge.

**Comment by mikeschinkel** [comment]
@embano1 — Thanks. Done.

The CLA form was not previously working in Chrome on my Mac but I just tried with my iPad and it worked.

**Comment by embano1** [comment]
PTAL at the failing unit test (doc verification)

**Comment by mikeschinkel** [comment]
@embano1:

 _” Error: The operation was canceled.”_

???

**Comment by embano1** [comment]
> @embano1:
> 
> _” Error: The operation was canceled.”_
> 
> ???

Argh, my bad...I meant the `govc` tests: https://github.com/vmware/govmomi/runs/6385461816?check_suite_focus=true#step:5:238

**Comment by mikeschinkel** [comment]
@embano1 — I updated `USAGE.md`.

Question: Since `USAGE.md` is automatically generated, why have CI check to see if it has been updated rather than just go ahead and update automatically?

**Comment by embano1** [comment]
> @embano1 — I updated `USAGE.md`.

Thx!

> Question: Since `USAGE.md` is automatically generated, why have CI check to see if it has been updated rather than just go ahead and update automatically?  

Are you asking for automatically updating it within the PR (separate commit) or after the PR is merged?

First does not work due to the way Github Actions and forked PRs work.

Latter is not encouraged as we want all changes to be hermetic and self-sufficient, including docs. If we'd have to roll back any PR/changes, it is much easier for us this way.

**Comment by mikeschinkel** [comment]
@embano1 — Thank you for the explanation.  

The reason I asked is that it makes submitted a tiny docs fix as a PR that appeared to me it would only take a minute but has turned into rather a production. For some reason the the build is failing again, I have no idea why, and I really didn't expect to have to learn the build system to be able make a tiny docs fix.  

I'm not complaining, I am just pointing at that friction like this discourages people from submit PRs. #fwiw.

**Comment by embano1** [comment]
> The reason I asked is that I submitted a tiny docs fix as a PR that appeared it would only take a minute but has turned into rather a production. For some reason the the build is failing again, I have no idea why, and I really didn't expect to have to learn the build system to be able make a tiny docs fix.  

Sorry for the trouble. I need to add this particular item to the `CONTRIBUTING` guide since it is only required for changes to the `govc` codebase.

The pipeline issues keep hunting us mostly since there was a change to the async code path in vcsim, leading to hard to troubleshoot races. We haven't had the time to investigate and fix them and typically tell contributors during PRs to ignore such (since it's not related to the contribution at all). I know, it's a pain. So sorry again for the hassle. 

> I'm not complaining, I am just pointing at that friction like this discourages people from submit PRs. #fwiw.

No offense taken, I'll discuss this with the team. This is important feedback. cc/ @dougm

**Review by embano1 — APPROVED** [review]
Thank you!

**Comment by mikeschinkel** [comment]
@embano1 — It’s all good. And thanks for hearing the feedback.

**Comment by mikeschinkel** [comment]
@embano1 — And yes, a quick note about how to contribute and about the failing CI/CD would appreciated by anyone else that contributes in the future, I’m sure.

**Comment by embano1** [comment]
> @embano1 — And yes, a quick note about how to contribute and about the failing CI/CD would appreciated by anyone else that contributes in the future, I’m sure.

QQ: you did see the [CONTRIBUTING](https://github.com/vmware/govmomi/blob/master/CONTRIBUTING.md) doc, did you? I just need to amend the `make docs` issue.

**Comment by mikeschinkel** [comment]
@embano1 — Sorry, I misspoke. Yes I did see that.  It was mostly about code and not docs.

I meant to write _"a quick note in `CONTRIBUTING.md` about how to contribute to `govc`"_ instead of the less accurate words I used above.

Also, I did miss the mention of including `govc:` prefix in the commit message. 

Sorry about both of those.

**Comment by embano1** [comment]
No worries at all and thy for highlighting the missing docs section!

**Pull request merged**
