### PR TITLE
vcsim: avoid race in ViewManager

### LINKED ISSUE #1620: data race in simulator/view_manager
Found while goroutines were using the same ViewManager

```
WARNING: DATA RACE
Write at 0x00c00050c0a0 by goroutine 94:
  github.com/vmware/govmomi/simulator.(*ViewManager).CreateContainerView()
      C:/Users/toomasp/IdeaProjects/vcenter_scanner.go/vendor/github.com/vmware/govmomi/simulator/view_manager.go:122 +0x737

Previous read at 0x00c00050c0a0 by goroutine 25:
  github.com/vmware/govmomi/simulator.(*ViewManager).Reference()
      <autogenerated>:1 +0x74
  github.com/vmware/govmomi/simulator.(*Registry).locker()
      C:/Users/toomasp/IdeaProjects/vcenter_scanner.go/vendor/github.com/vmware/govmomi/simulator/registry.go:505 +0xf2
```

### PR DESCRIPTION
**Pull request by dougm**
Fixes #1620

### CODE REVIEW

**Comment by toomasp** [comment]
Unfortunately the test itself is not reliable as it should be - ie, consecutive runs give different results. Thus even if the CI passes there might be doubts. But I've no clue as to how to get it to trigger reliably. Larger values of m.Datacenter / m.Datastore seem to increase the likelyhood.

**Comment by dougm** [comment]
@toomasp CI did actually fail, and I was able to reproduce locally.  It was a different race, pushed another commit to avoid that.

**Comment by toomasp** [comment]
LGTM

**Comment by dougm** [comment]
Thanks again @toomasp

**Pull request merged**
