### PR TITLE
allow to specify output format for recent tasks

### PR DESCRIPTION
**Pull request by breunigs**
(I am aware I (or rather my employer) needs to sign the CLA, but I am not quite sure how to get a company CLA. Let's see if the link the bot posts makes this clearer. FWIW, I [asked this on Slack](https://vmwarecode.slack.com/archives/C3DMXEL31/p1618988917009700) as well.)

Allow to output recent tasks in a machine readable format, e.g. JSON or XML. It will emit one document per received task update, including progress updates. This is useful when further processing/analysis is desired, fields are cut off (e.g. Target/`EntityName`) or absent in the standard table (e.g. message in `Result` referring to a just created VMDK).

Example usage and output:
```
$ govc tasks -f -l -json     

{"TaskName":"Reconfigure virtual machine","TaskInfo":{"Key":"task-12345","Task":{"Type":"Task","Value":"task-12345"},"Description":null,"Name":"ReconfigVM_Task","DescriptionId":"VirtualMachine.reconfigure","Entity":{"Type":"VirtualMachine","Value":"vm-101004"},"EntityName":"some-machine1.example.com","Locked":null,"State":"success","Cancelled":false,"Cancelable":false,"Error":null,"Result":null,"Progress":0,"Reason":{"UserName":"VSPHERE.LOCAL\\some-user"},"QueueTime":"2021-04-26T09:21:05.48933Z","StartTime":"2021-04-26T09:21:05.494609Z","CompleteTime":"2021-04-26T09:21:05.732256Z","EventChainId":78429326,"ChangeTag":"","ParentTaskKey":"","RootTaskKey":"","ActivationId":""}}
{"TaskName":"Reconfigure virtual machine","TaskInfo":{"Key":"task-12346","Task":{"Type":"Task","Value":"task-12346"},"Description":null,"Name":"ReconfigVM_Task","DescriptionId":"VirtualMachine.reconfigure","Entity":{"Type":"VirtualMachine","Value":"vm-103139"},"EntityName":"some-machine2.example.com","Locked":null,"State":"success","Cancelled":false,"Cancelable":false,"Error":null,"Result":null,"Progress":0,"Reason":{"UserName":"VSPHERE.LOCAL\\some-user"},"QueueTime":"2021-04-26T09:21:05.465536Z","StartTime":"2021-04-26T09:21:05.46998Z","CompleteTime":"2021-04-26T09:21:05.916864Z","EventChainId":78429325,"ChangeTag":"","ParentTaskKey":"","RootTaskKey":"","ActivationId":""}}
{"TaskName":"Reconfigure virtual machine","TaskInfo":{"Key":"task-123457","Task":{"Type":"Task","Value":"task-123457"},"Description":null,"Name":"ReconfigVM_Task","DescriptionId":"VirtualMachine.reconfigure","Entity":{"Type":"VirtualMachine","Value":"vm-102457"},"EntityName":"some-machine3.example.com","Locked":null,"State":"success","Cancelled":false,"Cancelable":false,"Error":null,"Result":null,"Progress":0,"Reason":{"UserName":"VSPHERE.LOCAL\\some-user"},"QueueTime":"2021-04-26T09:21:08.479443Z","StartTime":"2021-04-26T09:21:08.486538Z","CompleteTime":"2021-04-26T09:21:08.789729Z","EventChainId":78429330,"ChangeTag":"","ParentTaskKey":"","RootTaskKey":"","ActivationId":""}}
…
```

### CODE REVIEW

**Comment by embano1** [comment]
Thank you for your contribution @breunigs. Let us know if the information provided by the bot is helpful.

**Comment by breunigs** [comment]
Yes, I think the bot's link answered all my questions. I have passed it on internally, but this process usually takes a while.

**Comment by embano1** [comment]
Could you please also update the PR description with some detail on why this change is helpful and a quick summary of the changes introduced?

**Comment by embano1** [comment]
@breunigs looks like the CLA is not signed yet, correct?

**Comment by breunigs** [comment]
Yes, sorry, and it will take a while. The process my org uses for this is "single point of failure" which has been triggered due to sickness. Since this is not business critical, I also cannot/would not escalate this. So yeah, I can't give an ETA but I'll keep at it.

**Comment by embano1** [comment]
@breunigs just wanted to see if you want to get this one in before the next release?

**Comment by breunigs** [comment]
I don't think so. I am not in the position to sign the CLA, I need someone else to sign it for me. However, this person cannot access the CLA link, plus there's no option for them to also allow contributions from this account. 

The only option I see would be for them to clone this PR and submit it under their own account, which is a pretty weird flow. Any advice?

**Comment by breunigs** [comment]
closing in favor of https://github.com/vmware/govmomi/pull/2583 because the CLA signing is clearer for that PR

**Pull request closed without merging**
