### PR TITLE
govc: Add feature sso.*.ls to use the FindGroupsInGroup and FindUsersInGroup methods

### PR DESCRIPTION
**Pull request by abonat**
## Description

A new govc to list Groups in Group using the FindGroupsInGroup method, which is already here.
The FindGroupsInGroup is now available in the ssoadmin package
Tools like Ansible can read the state before do any change when add Groups in Group.
The check mode in Ansible modules can work also.

Closes: #2945

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [X] This change requires a documentation update
- [ ] Build related change

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. If applicable, please also list any relevant
details for your test configuration.

- [X] govmomi/govc$ go run . sso.group.lsgroups -json syncusers outputs the json correctly
`[
  {
    "Id": {
      "Name": "DnsAdmins",
      "Domain": "corp.local"
    },
    "Alias": {
      "Name": "DnsAdmins",
      "Domain": "CORPLOCAL"
    },
    "Details": {
      "Description": "DNS Administrators Group"
    }
  }
]`
- [X] Tested without options and without name (default to users@vsphere.local)

## Checklist:

- [X] My code follows the `CONTRIBUTION`
  [guidelines](https://github.com/vmware/govmomi/blob/master/CONTRIBUTING.md) of
  this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Comment by dougm** [comment]
Thanks @abonat , this looks good. How about we integrate with the existing sso.group.ls command, rather than add a new one?  See examples in the patch below
```diff
diff --git a/govc/sso/group/ls.go b/govc/sso/group/ls.go
index fa3b23bd..285e3e5d 100644
--- a/govc/sso/group/ls.go
+++ b/govc/sso/group/ls.go
@@ -33,6 +33,8 @@ import (
 type ls struct {
        *flags.ClientFlag
        *flags.OutputFlag
+
+       search string
 }
 
 func init() {
@@ -45,13 +47,21 @@ func (cmd *ls) Register(ctx context.Context, f *flag.FlagSet) {
 
        cmd.OutputFlag, ctx = flags.NewOutputFlag(ctx)
        cmd.OutputFlag.Register(ctx, f)
+
+       f.StringVar(&cmd.search, "s", "", "Search")
+}
+
+func (cmd *ls) Usage() string {
+       return "[NAME]"
 }
 
 func (cmd *ls) Description() string {
        return `List SSO groups.
 
 Examples:
-  govc sso.group.ls -s`
+  govc sso.group.ls
+  govc sso.group.ls group-name # list groups in group-name
+  govc sso.group.ls -s Admin # search for groups`
 }
 
 func (cmd *ls) Process(ctx context.Context) error {
@@ -76,14 +86,17 @@ func (r groupResult) Write(w io.Writer) error {
 }
 
 func (cmd *ls) Run(ctx context.Context, f *flag.FlagSet) error {
-       arg := f.Arg(0)
-
        return sso.WithClient(ctx, cmd.ClientFlag, func(c *ssoadmin.Client) error {
-               info, err := c.FindGroups(ctx, arg)
-               if err != nil {
-                       return err
+               if f.NArg() == 0 {
+                       info, err := c.FindGroups(ctx, cmd.search)
+                       if err != nil {
+                               return err
+                       }
+                       return cmd.WriteResult(groupResult(info))
                }
 
-               return cmd.WriteResult(groupResult(info))
+               // TODO: FindGroupInGroups(f.Arg(0))
+
+               return nil
        })
 }
```

**Comment by abonat** [comment]
Hello,
It makes sense to combine with the existing 'ls' command.
So we should also keep in mind that currently ls with a group name as parameter returns the users in the group.
So we should keep this behavior and add an additional output to the existing one.
Because I think some software already rely on this current output.
I mean the challenge here is somehow to combine both the outputs with single json output

**Comment by dougm** [comment]
> currently ls with a group name as parameter returns the users in the group

param currently is used as the option search string:
```console
% govc sso.group.ls Admin
DCAdmins                                     
LicenseService.Administrators                License Service Administrators
CAAdmins                                     
...
% govc sso.group.ls Admin | wc -l
13
% govc sso.group.ls | wc -l
29
```

My proposed change would just be to add a `-s` flag for the search string, and if a param is given FindGroupsInGroup.
I doubt there's much existing code using the current search param, but we can document the breaking change: https://github.com/vmware/govmomi/blob/master/CONTRIBUTING.md#example-5---document-breaking-api-changes

**Comment by abonat** [comment]
I did your proposes and also did similar for sso.user.ls  to show users in particular group when specify a group name. Example:  sso.user.ls -group SyncUsers list the users in group SyncUsers

**Review by dougm — APPROVED** [review]
Thanks @abonat !

**Pull request merged**
