### PR TITLE
vcsim: Fix Data race in unprotected simulator.Map

### PR DESCRIPTION
**Pull request by awsaba**
Close: #2750

## Description

There is data race when reinitialized the global `simulator.Map` during tests. This changes is to wrap access and re- initialization using singleton style functions with a corresponding mutex.

Closes: #2570

## Type of change

Please mark options that are relevant:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. If applicable, please also list any relevant
details for your test configuration.

- [ ] `make check`: 2 tests FAIL also fail on `master`
- [ ] Testing the simulator package directly with `-race -count 100`: 

```
GORACE=atexit_sleep_ms=10000 /usr/local/bin/go test -count 100 \
  -race \
  -timeout 10m \
  -v  \
  ./simulator/... | tee out.txt
```

**Test Configuration**:

* Toolchain: go 1.17
* SDK:
* (add more if needed)

## Checklist:

- [x] My code follows the CONTRIBUTION [guidelines](./../CONTRIBUTING.md) of
  this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Comment by awsaba** [comment]
cc @protochron

**Comment by dougm** [comment]
Thank you @awsaba !  I'm behind on govmomi issues+PRs, but will get to fully reviewing this soon.  The other part of the hold up is me kicking myself for adding the package var (`Map`) to begin with.  The `simulator.Map` seemed like a convenience originally, but long term we'd like to get rid of the package var.  Will share some more thoughts on that soon.  cc @akutz

**Comment by awsaba** [comment]
> What do others think?

@dougm @akutz Thanks for the insight, this discussion has really helped.

>  We would need to make the Context param required. There are also methods that currently include Context in their signature, but still use Map directly, instead of ctx.Map, but those would be simple to fix up.

Looking at the error from #2571 and the other common ones that we see in CI, that method at least is one of these that takes a `Context` but doesn't use `ctx.map`. Smaller changes to change that and some locking in our fixtures around repeated calls to `Simulator.Create` may be enough to reduce how often it hits, so I'll be happy to close this PR and start with some smaller changes around that as a path forward while some of the higher level planning happens.

**Comment by dougm** [comment]
> > We would need to make the Context param required. There are also methods that currently include Context in their signature, but still use Map directly, instead of ctx.Map, but those would be simple to fix up.
> 
> Looking at the error from #2571 and the other common ones that we see in CI, that method at least is one of these that takes a `Context` but doesn't use `ctx.map`. Smaller changes to change that and some locking in our fixtures around repeated calls to `Simulator.Create` may be enough to reduce how often it hits, so I'll be happy to close this PR and start with some smaller changes around that as a path forward while some of the higher level planning happens.

Thanks @awsaba , I think it would be good to move forward with both if you're up for it:
- make the Context param required for method impls
- use ctx.Map instead of Map directly in those methods

Might be better to have those as 2 PRs, or more, up to you. I think we'll want to do this, regardless of if a separate "v2" comes to be, as we'll reuse much of "v1". Hope to see you in the community zoom when we get that setup!

**Comment by awsaba** [comment]
Closing in favor of multiple PRs to use `ctx.Map` and require it where necessary and further discussion on bigger breaking changes.

**Pull request closed without merging**
