### PR TITLE
New -net.dvpg argument in NetworkFlag for picking a DistributedVirtualPortgroup

### PR DESCRIPTION
**Pull request by eyz**
Usage (such as with vm.create):

-net.dvpg= (Distributed Virtual Portgroup inventory path)

This has been tested with vm.create. I also verified that the existing -net option works as expected in my tests with vm.create. If the -net.dvpg option is specified then the existing -net option will not be used.

### CODE REVIEW

**Comment by eyz** [comment]
NOTE: once I find the best way to query the DistributedVirtualSwitch by its key (such as "dvs-###") without an exhaustive search I will remove the requirement for the -port.dvs option, as that object it will be obtained programmatically from the DistributedVirtualPortgroup object

**Comment by dougm** [comment]
@eyz thanks, planning to review your PRs soon.  Might need to rebase against vmware/master to pick up 6e991fc so CI is happy.

**Comment by eyz** [comment]
@dougm: merged vmware/govmomi master to eyz/govmomi branches

**Comment by eyz** [comment]
@dougm: Looks like the drone build failed, but if you find my PR is somehow responsible please let me know how I can assist

**Comment by eyz** [comment]
To my eye, it looks like test .vmx cannot be found -

not ok 17 device.info
# (from function `flunk' in file govc/test/test_helper.bash, line 165,
#  from function `assert_success' in file govc/test/test_helper.bash, line 170,
#  in test file govc/test/device.bats, line 16)
#   `assert_success' failed
# govc: An error occurred while writing dictionary file "/vmfs/volumes/56e33959-0d4d2de8-ca00-0050561d658a/govc-test-c1ae0c71-a7fc-4be8-beca-0996fe61b229/govc-test-c1ae0c71-a7fc-4be8-beca-0996fe61b229.vmx": 2 (No such file or directory).
# command failed with exit status 1: govc: vm 'govc-test-c1ae0c71-a7fc-4be8-beca-0996fe61b229' not found

**Comment by dougm** [comment]
@eyz Not seeing how -net.dvpg would be different from using -net (which already supports DVPG values).

**Comment by eyz** [comment]
@dougm I didn't have luck when I tried adding to a DVPG. Perhaps I didn't try an inventory path though. I'll try again.

**Comment by eyz** [comment]
@dougm Yes, I'm confirmed that -net can take an inventory path to a DVPG, and in our environment. A few weeks ago when I tried to add a DVPG, I only passed in the final portion of the path, not the full path; adding a non-DVPG doesn't require a full path. I don't recall finding any documentation regarding when an inventory path has to be specified, so perhaps that is the best takeaway. You can close this.

**Pull request closed without merging**
