### PR TITLE
vcsim: add support to override credentials

### LINKED ISSUE #1487: Request for vcsim - validation of credentials
I'm adding support for secure Kubernetes secrets to the vcenter-connector [1], but have no access to vCenter to test it out. I wanted to use vcsim [2], but realised that it doesn't allow overriding of credentials for the simulated server, or validate the password.

I can understand this may be OK for MVP, but I think it would help people making use of vcsim if it A) validated the credentials it prints out in debug B) allowed for them to be provided via a flag.

Thanks again for your work :beers:  

[1] https://github.com/openfaas-incubator/vcenter-connector

[2] https://github.com/vmware/govmomi/tree/master/vcsim

### PR DESCRIPTION
**Pull request by dougm**
Fixes #1487

### CODE REVIEW

**Comment by dougm** [comment]
@alexellis does this suffice?  We could also add a separate flag, but with this PR you can include username:password with the existing `-l` flag, for example: `vcsim -l nobody:nothing@127.0.0.1:8989`

**Comment by alexellis** [comment]
I might be being a bit pedantic, but I'd separate out the listening from the credentials and also allow them to be taken in via file (for use in Kubernetes).

Ideally:

```
--credentials nobody:nothing
--credentials-from /var/run/secret/basic-auth
```

More verbose might be:

```
--user nobody
--password nothing
--user-from /var/run/secret/basic-auth-user
--password-from  /var/run/secret/basic-auth-password
```

**Comment by dougm** [comment]
I'm ok with adding more flag(s), using `-l` just avoided have to decide how many flags and their names :)

What do you think about `--username` and `--password`, where if the value is a file (checking via Stat), we source from the file?  Else use the literal value of the flags.

Was also thinking about this for govc, with #1352 where the client secrets can be specified via `GOVC_USERNAME` and `GOVC_PASSWORD`.

Either way, would like to keep it consistent between govc and vcsim, I'm open having separate `-from` flags for both the username and password.

**Comment by alexellis** [comment]
Sounds workable, thanks :+1:

**Comment by dougm** [comment]
@alexellis ok updated, thanks for reviewing.

**Pull request merged**
