### PR TITLE
Add Reauth flag to skip loading cached sessions

### PR DESCRIPTION
**Pull request by royling**
Closes: #2512 

## Type of change

Please mark options that are relevant:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide
instructions so we can reproduce. If applicable, please also list any relevant
details for your test configuration.

- [ ] Test Description 1
- [ ] Test Description 2

**Test Configuration**:
* Toolchain:
* SDK:
* (add more if needed)

## Checklist:

- [x] My code follows the CONTRIBUTION [guidelines](./../CONTRIBUTING.md) of
  this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Review by dougm — COMMENTED** [review]
Thanks @royling , could you add a comment/doc on the use case of `Reauth` vs `Passthrough` ?

**Comment by royling** [comment]
Sure, I will update this.

Btw, from my point of view, I wanted to add this flag to address the issue I described in #2512. Do you think what may be a better name for the flag? `ForceLogin` or `Reauth`?

**Comment by royling** [comment]
Added doc for `Reauth` flag.

**Review by dougm — APPROVED** [review]
Sorry for the delay @royling , looks good, thanks!

**Pull request merged**
