### PR TITLE
Fixed error when attempting to access datastore

### PR DESCRIPTION
**Pull request by mrbobbytables**
Encountered this when trying to spin up kubernetes cluster on vsphere. More changes may be needed.

### CODE REVIEW

**Comment by pietern** [comment]
@mrbobbytables I checked with our legal team and they haven't received it. Would you mind resubmitting to osscontributions@vmware.com ? Thanks.

**Comment by mrbobbytables** [comment]
I think I know why it wasn't received. I just forwarded it again and got
this:

Your mail to 'Osscontributions' with the subject

    Fwd: Robert Killen OSS agreement

Is being held until the list moderator can review it for approval.

The reason it is being held:

    Message body is too big: 1711089 bytes with a limit of 1024 KB

Either the message will get posted to the list, or you will receive
notification of the moderator's decision.  If you would like to cancel
this posting, please visit the following URL.

I must have missed that last time

-Bob

On Tue, Feb 10, 2015 at 12:10 PM, Pieter Noordhuis <notifications@github.com

**Comment by pietern** [comment]
@mrbobbytables OK, thanks for letting me know. Can you send it to pnoordhuis@vmware.com? I'll make sure it lands where it needs to be...

**Comment by mrbobbytables** [comment]
Done. Please don't hesitate to let me know if there are any further issues.

On Tue, Feb 10, 2015 at 12:17 PM, Pieter Noordhuis <notifications@github.com

**Comment by pietern** [comment]
Thank you!

**Comment by dougm** [comment]
cherry-picked the change + gofmt'd, thanks @mrbobbytables !

**Pull request closed without merging**
