### PR TITLE
govc: fix default guest.run path for unsupported Windows guests

### PR DESCRIPTION
**Pull request by dougm**
- Add '-w' flag to guest.run

Closes: #2446

### CODE REVIEW

**Comment by embano1** [comment]
Thx Doug, I'm fine with the code changes but was wondering why we don't allow to overwrite the SHELL but depend on the OS type instead? Wouldn't changing the SHELL be more flexible instead of introducing that new windows specific parameter?

**Comment by dougm** [comment]
@embano1 we can override if an absolute path is given, for example:
```console
% govc guest.run -vm foo /usr/local/bin/any-program ...
```
The os family based `bash -c` and `cmd.exe /c` defaults when non-absolute path is given is just for convenience.
We could live without the new `-w` flag, in this case that would mean having to specify:
```console
% govc guest.run -vm foo c:\\Windows\\System32\\cmd.exe /c powershell c:\\bar.ps1
```
Instead of:
```console
% govc guest.run -vm foo -w powershell c:\\bar.ps1
```

**Comment by embano1** [comment]
Thx for confirming my assumption that this is possible today, but adding `-w` is a convenience  feature. Do you foresee other combinations or more flags where this would be needed or is Windows the exception here?

**Comment by dougm** [comment]
Yeah, windows is the exception.  Instead of adding `-w`, we could instead do the change below, toolsInstallType would only ever be `MSI` on Windows guests. What do you think?

```diff
modified   govc/vm/guest/guest.go
@@ -88,12 +88,18 @@ func (flag *GuestFlag) Toolbox() (*toolbox.Client, error) {
 
 	family := ""
 	var props mo.VirtualMachine
-	err = vm.Properties(context.Background(), vm.Reference(), []string{"guest.guestFamily"}, &props)
+	err = vm.Properties(context.Background(), vm.Reference(), []string{"guest.guestFamily", "guest.toolsInstallType"}, &props)
 	if err != nil {
 		return nil, err
 	}
 	if props.Guest != nil {
 		family = props.Guest.GuestFamily
+		if family == string(types.VirtualMachineGuestOsFamilyOtherGuestFamily) {
+			if props.Guest.ToolsInstallType == string(types.VirtualMachineToolsInstallTypeGuestToolsTypeMSI) {
+				// The case of Windows version not supported by the ESX version
+				family = string(types.VirtualMachineGuestOsFamilyWindowsGuest)
+			}
+		}
 	}
 
 	return &toolbox.Client{
```

**Comment by embano1** [comment]
Nice, I like that much better! No (breaking) change for user and it will behave accordingly to what users would expect (see issue).

**Comment by dougm** [comment]
ok, done @embano1 👍

**Review by embano1 — APPROVED** [review]
LGTM

**Pull request merged**
