### PR TITLE
Fix 502 on WaitForIP with retry

### PR DESCRIPTION
**Pull request by arouene**
Implement a simple retry on WaitForIP, as I always get "502 Proxy error" on the first try on vSphere 6.5.

Here the requests from my error :
```
==> centos-8.0-x86_64-server: Waiting for IP...
2019/12/18 10:10:13 REQ: <Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/"><Body><CreateFilter xmlns="urn:vim25"><_this type="PropertyCollector">session[527c8b84-b5ac-4877-30f9-afb55b975aaf]52f587bd-a995-089a-92b0-f5cc137d58cb</_this><spec><propSet><type>VirtualMachine</type><pathSet>guest.ipAddress</pathSet></propSet><objectSet><obj type="VirtualMachine">vm-144</obj></objectSet></spec><partialUpdates>false</partialUpdates></CreateFilter></Body></Envelope>
2019/12/18 10:10:13 RES: 200
2019/12/18 10:10:13 REQ: <Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/"><Body><WaitForUpdatesEx xmlns="urn:vim25"><_this type="PropertyCollector">session[527c8b84-b5ac-4877-30f9-afb55b975aaf]52f587bd-a995-089a-92b0-f5cc137d58cb</_this></WaitForUpdatesEx></Body></Envelope>
2019/12/18 10:10:13 RES: 200
2019/12/18 10:10:13 REQ: <Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/"><Body><WaitForUpdatesEx xmlns="urn:vim25"><_this type="PropertyCollector">session[527c8b84-b5ac-4877-30f9-afb55b975aaf]52f587bd-a995-089a-92b0-f5cc137d58cb</_this><version>1</version></WaitForUpdatesEx></Body></Envelope>
2019/12/18 10:15:13 RES: 502
2019/12/18 10:15:13 REQ: <Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/"><Body><DestroyPropertyCollector xmlns="urn:vim25"><_this type="PropertyCollector">session[527c8b84-b5ac-4877-30f9-afb55b975aaf]52f587bd-a995-089a-92b0-f5cc137d58cb</_this></DestroyPropertyCollector></Body></Envelope>
2019/12/18 10:15:13 RES: 200
2019/12/18 10:15:16 REQ: <Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/"><Body><CreatePropertyCollector xmlns="urn:vim25"><_this type="PropertyCollector">propertyCollector</_this></CreatePropertyCollector></Body></Envelope>
2019/12/18 10:15:16 RES: 200
2019/12/18 10:15:16 REQ: <Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/"><Body><CreateFilter xmlns="urn:vim25"><_this type="PropertyCollector">session[527c8b84-b5ac-4877-30f9-afb55b975aaf]52520ddd-6ddc-7ef2-6130-3fc2cba4446b</_this><spec><propSet><type>VirtualMachine</type><pathSet>guest.ipAddress</pathSet></propSet><objectSet><obj type="VirtualMachine">vm-144</obj></objectSet></spec><partialUpdates>false</partialUpdates></CreateFilter></Body></Envelope>
2019/12/18 10:15:16 RES: 200
```

I think it's related to that issue : https://github.com/jetbrains-infra/packer-builder-vsphere/issues/211
That Packer plugin is using govmomi.

The retry is a simple, on error try 3 time max, with 3 seconds sleep each time.

### CODE REVIEW

**Comment by dougm** [comment]
@arouene see #1758 and the example in particular.  It extends the existing retry mechanism to more easily support HTTP status codes.  Would that work for you?

**Comment by arouene** [comment]
@dougm Ok, I'm testing that with #1758 !

**Comment by arouene** [comment]
@dougm It will need your PR #1758 as I didn't include it in my commit.

Also I had to add a method on Collector, to set the RoundTripper on the Collector instead of modifying the default one on vim25.Client, hope it's ok to do it like that.

**Comment by arouene** [comment]
@dougm Oh ok, alright. So I will just close this PR ! Thanks for you work !

**Pull request closed without merging**
