### PR TITLE
Add chore section to CHANGELOG

### PR DESCRIPTION
**Pull request by embano1**
Will add this to CHANGELOG.md (and every release) highlighting all commits with `chore: ...` prefix.

Example:

<a name="v0.25.0-next"></a>
## [Release v0.25.0-next](https://github.com/vmware/govmomi/compare/v0.26.0...v0.25.0-next)

> Release Date: 2021-05-05

### 💫 `vcsim` (Simulator)

- add guest operations process support

### 🧹 Chore

- Add issue greeting
- Add WIP Action
- Remove dep files
- Clean up documentation
- Remove unused release script
- Automate CHANGELOG

### 📖 Commits

- Add chore section to CHANGELOG [e39dfdc8]
- chore: Add issue greeting [cac1d8d7]
- chore: Add WIP Action [0f1c3f89]
- chore: Remove dep files [921ad37a]
- docs: Document linker and GOFLAGS for build vars [2719c229]
- Clarify SetRootCAs behavior [f3645a96]
- toolbox: add hgfs freebsd stub [c368e57f]
- vcsim: add guest operations process support [35a42af5]
- Set RoundTripper in ssoadmin.NewClient [64e55d81]
- chore: Clean up documentation [1d4ce94a]
- chore: Remove unused release script [991278b9]
- chore: Automate CHANGELOG [16d8add5]
- Add NotFoundFault in cns types [e8805c92]

Closes: #2410
Signed-off-by: Michael Gasch <mgasch@vmware.com>

### CODE REVIEW

**Comment by embano1** [comment]
@dougm what do you think about this change to highlight (certain) repo activities (after the govc/vcsim sections)?

**Review by dougm — DISMISSED** [review]
Sounds good to me 👍

**Comment by dougm** [comment]
Maybe another :chore: , would be great to doc these ChangeLog prefixes in https://github.com/vmware/govmomi/blob/master/CONTRIBUTING.md#format-of-the-commit-message

And maybe the bot welcome message could include a link to CONTRIBUTING.md ?

**Comment by embano1** [comment]
Two great points! Will do!

**Comment by embano1** [comment]
@dougm ready to go

**Review by dougm — APPROVED** [review]
Thanks @embano1

**Pull request merged**
